# Generated by Django 2.2.3 on 2020-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200622_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft1', 'Draft'), ('published', 'Published')], default='draft1', max_length=10),
        ),
    ]
